//IMAGINE THIS IS A PIECE OF JS CODE WRITTEN BY SOMEONE ELSE
//HOWEVER THIS IS BAD CODE BECAUSE IT POLLUTES THE GLOBAL NAMESPACE

var person = 'Steve';

function logPerson(){
	console.log(person);
}

//BY THE TIME THIS FUNCTION IS CALLED IN APP.JS, THE VARIABLE PERSON
//HAS BEEN OVERWRITTEN BY THE SAME VARIABEL DECLARATION IN APP.JS